# See config.example.yml for documentation.
object_base: orig/RHMEE9
object: sys/main.dol
hash: 78cdbf39b231b351be4c0d789f0b141db606405e
symbols: config/RHMEE9/symbols.txt
splits: config/RHMEE9/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
